"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SorobanAssetMethods = void 0;
var SorobanAssetMethods;
(function (SorobanAssetMethods) {
    SorobanAssetMethods["allowance"] = "allowance";
    SorobanAssetMethods["approve"] = "approve";
    SorobanAssetMethods["balance"] = "balance";
    SorobanAssetMethods["spendable_balance"] = "spendable_balance";
    SorobanAssetMethods["transfer"] = "transfer";
    SorobanAssetMethods["transfer_from"] = "transfer_from";
    SorobanAssetMethods["burn"] = "burn";
    SorobanAssetMethods["burn_from"] = "burn_from";
    SorobanAssetMethods["decimals"] = "decimals";
    SorobanAssetMethods["name"] = "name";
    SorobanAssetMethods["symbol"] = "symbol";
    SorobanAssetMethods["set_admin"] = "set_admin";
    SorobanAssetMethods["admin"] = "admin";
    SorobanAssetMethods["set_authorized"] = "set_authorized";
    SorobanAssetMethods["authorized"] = "authorized";
    SorobanAssetMethods["mint"] = "mint";
    SorobanAssetMethods["clawback"] = "clawback";
})(SorobanAssetMethods = exports.SorobanAssetMethods || (exports.SorobanAssetMethods = {}));
